- hosts: cubo
  remote_user: root
  become: yes
  become_method: sudo
  vars: 
    influxdb_hostname: 'cubo'
    influxdb_internet_connection: true

  roles:
    - base
    - common
    - monitoring
    - chillAtHome