- hosts: cubo
  remote_user: root
  become: yes
  become_method: sudo
  vars: 
    influxdb_ip: '127.0.0.1'
    influxdb_hostname: 'cubo'
    

  roles:
    - common
    - monitoring
    - spark
    - chillAtHome