- hosts: cubo
  remote_user: root
  become: yes
  become_method: sudo
  vars: 
    influxdb_ip: '127.0.0.1'
    influxdb_hostname: 'cubo'
    influxdb_internet_connection: true
    influxdb_has_docker: false

  roles:
    - base
    - common
    - monitoring
    - chillAtHome