---

- name: k3s server
  k3s_server:
    datastore-endpoint: postgres://postgres:verybadpass@database:5432/postgres?sslmode=disable
    docker: true
    cluster-cidr: 172.20.0.0/16
    flannel-backend: 'none'  # This needs to be in quotes
    disable:
      - traefik
      - coredns
  

