- name: Start service docker, if not running
  service:
    name: docker
    state: started

- name: Docker images
  docker_service:
    project_name: fragugliaserver
    pull: yes
    restarted: yes
    definition:
      version: '3.6'
      services:
        jenkins:
          container_name: jenkins
          image: 'jenkins/jenkins:latest'
          network_mode: "host"
          volumes:
            - '/home/server0/configuration/Jenkins:/var/jenkins_home'
          user: "20000:20000"
- file:
    path: /home/server0
    owner: server0
    group: server0
    recurse: yes
    state: directory
