---

- name: Base packages
  apt:
    name:
      - 'rclone'
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Create plex transcode scratch dir
  file: path={{ item }} owner=server0 group=server0 recurse=true state=directory
  with_items:
    - /var/scratch/plex_transcode

- name: Chill
  docker_compose:
    project_name: fragugliaserver
    pull: true
    restarted: true
    definition:
      version: '3.7'
      services:
        deluge:
          image: linuxserver/deluge
          container_name: deluge
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Deluge:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/downloads/movies
            - /opt/deluge_incomplete:/downloads/incomplete
          network_mode: host
          restart: always
        jackett:
          image: linuxserver/jackett
          container_name: jackett
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Jackett:/config
            - /home/server0/temp/ja_downloads:/downloads
          network_mode: host
          restart: always
        radarr:
          image: linuxserver/radarr
          container_name: radarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /opt/configuration/Radarr:/config
            - /home/backup/Radarr:/backup
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/movies
          network_mode: host
          restart: always
        sonarr:
          image: linuxserver/sonarr
          container_name: sonarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /opt/configuration/Sonarr:/config
            - /home/backup/Sonarr:/backup
            - /home/plex/tvshows:/tv
            - /home/plex/animeshows:/animeshows
            - /home/server0/temp/t_downloads:/downloads
          network_mode: host
          restart: always
        plex:
          image: linuxserver/plex
          container_name: plex
          network_mode: host
          environment:
            - PUID=20000
            - PGID=20000
            - VERSION=latest
          volumes:
            - /home/plex:/config
            - /home/plex/tvshows:/tv
            - /home/plex:/movies
            - /var/scratch/plex_transcode:/transcode
            - /var/scratch/plex_transcode_tmp:/tmp
          restart: always
        samba:
          container_name: samba
          restart: always
          image: dperson/samba
          volumes:
            - /home:/mount
          environment:
            - NMBD=true
            - PERMISSIONS=true
            - SMB=true
            - WORKGROUP=fraguglia.it
            - USERID=20000
            - GROUPID=20000
            - SHARE=backup;/home/backup;yes;no;no;riccardo;riccardo
            - SHARE2=plex;/mount/plex;yes;no;no;riccardo;riccardo
            - SHARE3=photos;/mount/photos;yes;no;no;riccardo,caroline;riccardo
            - SHARE4=downloads;/mount/server0/temp/t_downloads/complete;yes;no;no;riccardo;riccardo
            - USER=riccardo;{{ riccardo_password }}
            - USER2=caroline;{{ caroline_password }}
            - GLOBAL=domain master = Yes
            - GLOBAL2=ea support = Yes
            - GLOBAL3=fruit:metadata = stream
            - GLOBAL4=fruit:model = MacSamba
            - GLOBAL5=delete veto files = true
            - GLOBAL6=fruit:veto_appledouble = yes
            - GLOBAL7=fruit:posix_rename = yes
            - GLOBAL8=fruit:zero_file_id = yes
            - GLOBAL9=fruit:wipe_intentionally_left_blank_rfork = yes
            - GLOBAL10=fruit:delete_empty_adfiles = yes
            - GLOBAL11=log file = /var/log/samba/log.%m
            - GLOBAL12=server string = Penguin Power!
            - GLOBAL13=use sendfile = Yes
            - GLOBAL14=wins support = Yes
            - GLOBAL15=vfs objects = fruit streams_xattr
            - GLOBAL16=fruit:time machine = yes
          network_mode: host
        mariadb:
          image: linuxserver/mariadb
          container_name: mariadb
          environment:
            - PUID=20000
            - PGID=20000
            - MYSQL_ROOT_PASSWORD={{ server0_password }}
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/MariaDB:/config
          network_mode: host
          restart: always
        openhab:
          image: "openhab/openhab:latest"
          container_name: openhab
          restart: always
          network_mode: host
          volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/home/server0/configuration/OpenHAB/addons:/openhab/addons"
            - "/home/server0/configuration/OpenHAB/conf:/openhab/conf"
            - "/home/server0/configuration/OpenHAB/userdata:/openhab/userdata"
          environment:
            OPENHAB_HTTP_PORT: "9680"
            EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Paris"
            USER_ID: 20000
            GROUP_ID: 20000






