---

- name: Plex library mounted
  mount:
    path: /var/lib/plexmediaserver/Library
    src: /home/plex/Library
    fstype: none
    opts: bind,x-systemd.requires=zfs-mount.service,x-systemd.before=docker.service
    state: present

- name: Plex tvshow library mounted
  mount:
    path: /home/server0/data/Library/tvshows
    src: /home/plex/tvshows
    fstype: none
    opts: bind,x-systemd.requires=zfs-mount.service,x-systemd.before=docker.service
    state: present

- name: Create plex transcode scratch dir
  file: path={{ item }} owner=server0 group=server0 recurse=true state=directory
  with_items:
    - /var/scratch/plex_transcode

- name: Sickchill & Deluge docker images
  docker_compose:
    project_name: fragugliaserver
    pull: true
    restarted: true
    definition:
      version: '3.7'
      services:
        deluge:
          image: linuxserver/deluge
          container_name: deluge
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Deluge:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/downloads/movies
            - /opt/deluge_incomplete:/downloads/incomplete
          network_mode: host
          restart: always
        jackett:
          image: linuxserver/jackett
          container_name: jackett
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Jackett:/config
            - /home/server0/temp/ja_downloads:/downloads
          network_mode: host
          restart: always
        radarr:
          image: linuxserver/radarr
          container_name: radarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Radarr:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/movies
          network_mode: host
          restart: always
        sonarr:
          image: linuxserver/sonarr
          container_name: sonarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Sonarr:/config
            - /home/plex/tvshows:/tv
            - /home/server0/temp/t_downloads:/downloads
          network_mode: host
          restart: always
        plex:
          image: linuxserver/plex
          container_name: plex
          network_mode: host
          environment:
            - PUID=20000
            - PGID=20000
            - VERSION=docker
          volumes:
            - /home/plex:/config
            - /home/plex/tvshows:/tv
            - /home/plex:/movies
            - /var/scratch/plex_transcode:/transcode
          restart: always
        homeassistant:
          container_name: home-assistant
          image: homeassistant/home-assistant:stable
          volumes:
            - /home/server0/configuration/HASS:/config
          environment:
            - TZ=Europe/Paris
          restart: always
          network_mode: host
        samba:
          container_name: samba
          restart: always
          image: dperson/samba
          volumes:
            - /home:/mount
          environment:
            - NMBD=true
            - PERMISSIONS=true
            - SMB=true
            - WORKGROUP=fraguglia.it
            - USERID=20000
            - GROUPID=20000
            - SHARE=photo;/mount/photo;yes;no;no;riccardo,caroline;riccardo
            - SHARE2=plex;/mount/plex;yes;no;no;server0;server0
            - USER=riccardo;{{ riccardo_password }}
            - USER2=caroline;{{ caroline_password }}
            - GLOBAL=domain master = Yes
            - GLOBAL2=ea support = Yes
            - GLOBAL3=fruit:metadata = stream
            - GLOBAL4=fruit:model = MacSamba
            - GLOBAL5=delete veto files = true
            - GLOBAL6=fruit:veto_appledouble = yes
            - GLOBAL7=fruit:posix_rename = yes
            - GLOBAL8=fruit:zero_file_id = yes
            - GLOBAL9=fruit:wipe_intentionally_left_blank_rfork = yes
            - GLOBAL10=fruit:delete_empty_adfiles = yes
            - GLOBAL11=log file = /var/log/samba/log.%m
            - GLOBAL12=server string = Penguin Power!
            - GLOBAL13=use sendfile = Yes
            - GLOBAL14=wins support = Yes
          network_mode: host
        influxdb:
          image: influxdb:latest
          container_name: influxdb
          network_mode:
            host
          volumes:
            - /home/server0/configuration/InfluxDB:/var/lib/influxdb
          restart:
            always
          user: 
            20000:20000
        grafana:
          image: grafana/grafana
          container_name: grafana
          network_mode:
            host
          volumes:
            - /home/server0/configuration/Grafana:/var/lib/grafana
          restart:
            always
          user:
            20000:20000






