---
- name: Shorewall to be stopped
  service:
    name: shorewall
    state: stopped

- name: Sickchill & Deluge docker images
  docker_service:
    project_name: fragugliaserver
    pull: true
    restarted: true
    definition:
      version: '3.7'
      services:
        deluge:
          image: linuxserver/deluge
          container_name: deluge
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Deluge:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/downloads/movies
          network_mode: host
          restart: always
        radarr:
          image: linuxserver/radarr
          container_name: radarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Radarr:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/movies
          network_mode: host
          restart: always
        sonarr:
          image: linuxserver/sonarr
          container_name: sonarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Sonarr:/config
            - /home/plex/tvshows:/tv
            - /home/server0/temp/t_downloads:/downloads
          network_mode: host
          restart: always

- name: Plex apt keys
  apt_key: url={{ item }} state=present
  with_items:
    - https://downloads.plex.tv/plex-keys/PlexSign.key
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install plexmediaserver
  apt:
    deb: https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Plex to be stopped
  service:
    name: plexmediaserver
    state: stopped

- name: Plex library mounted
  mount:
    path: /var/lib/plexmediaserver/Library
    src: /home/plex/Library
    fstype: none
    opts: bind,x-systemd.requires=zfs-mount.service,x-systemd.before=plexmediaserver.service
    state: present

- name: Plex tvshow library mounted
  mount:
    path: /home/server0/data/Library/tvshows
    src: /home/plex/tvshows
    fstype: none
    opts: bind,x-systemd.requires=zfs-mount.service,x-systemd.before=plexmediaserver.service
    state: present

- name: host temp files in zfs
  lineinfile:
    path: /etc/default/plexmediaserver
    regexp: '^export PLEX_MEDIA_SERVER_TMPDIR'
    line: 'export PLEX_MEDIA_SERVER_TMPDIR=/home/plex/temp'

- name: run as user server0
  lineinfile:
    path: /etc/default/plexmediaserver
    regexp: '^export PLEX_MEDIA_SERVER_USER'
    line: 'export PLEX_MEDIA_SERVER_USER=server0'

- name: host temp files in zfs (to be sure)
  lineinfile:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: '^Environment\=PLEX_MEDIA_SERVER_TMPDIR'
    line: 'Environment=PLEX_MEDIA_SERVER_TMPDIR=/home/plex/temp'

- name: run as user server0 (to be sure)
  lineinfile:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: '^User\='
    line: 'User=server0'

- name: run as group server0 (to be sure)
  lineinfile:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: '^Group\='
    line: 'Group=server0'

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: Plex to be started
  service:
    name: plexmediaserver
    state: started

- name: Home for server0 exists
  file:
    path: /home/server0
    owner: server0
    group: server0
    recurse: true
    state: directory





