---
- name: Shorewall to be stopped
  service:
    name: shorewall
    state: stopped

- name: Plex library mounted
  mount:
    path: /var/lib/plexmediaserver/Library
    src: /home/plex/Library
    fstype: none
    opts: bind,x-systemd.requires=zfs-mount.service,x-systemd.before=plexmediaserver.service
    state: present

- name: Plex tvshow library mounted
  mount:
    path: /home/server0/data/Library/tvshows
    src: /home/plex/tvshows
    fstype: none
    opts: bind,x-systemd.requires=zfs-mount.service,x-systemd.before=plexmediaserver.service
    state: present

- name: Sickchill & Deluge docker images
  docker_service:
    project_name: fragugliaserver
    pull: true
    restarted: true
    definition:
      version: '3.7'
      services:
        deluge:
          image: linuxserver/deluge
          container_name: deluge
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Deluge:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/downloads/movies
          network_mode: host
          restart: always
        jackett:
          image: linuxserver/jackett
          container_name: jackett
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Jackett:/config
            - /home/server0/temp/ja_downloads:/downloads
          network_mode: host
          restart: always
        radarr:
          image: linuxserver/radarr
          container_name: radarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Radarr:/config
            - /home/server0/temp/t_downloads:/downloads
            - /home/plex:/movies
          network_mode: host
          restart: always
        sonarr:
          image: linuxserver/sonarr
          container_name: sonarr
          environment:
            - PUID=20000
            - PGID=20000
            - UMASK_SET=022
            - TZ=Europe/Paris
          volumes:
            - /home/server0/configuration/Sonarr:/config
            - /home/plex/tvshows:/tv
            - /home/server0/temp/t_downloads:/downloads
          network_mode: host
          restart: always
        plex:
          image: linuxserver/plex
          container_name: plex
          network_mode: host
          environment:
            - PUID=20000
            - PGID=20000
            - VERSION=docker
          volumes:
            - /home/plex:/config
            - /home/plex/tvshow:/tv
            - /home/plex:/movies
            - /home/plex/transcode:/transcode
          restart: always

- name: Home for server0 exists
  file:
    path: /home/server0
    owner: server0
    group: server0
    recurse: true
    state: directory





