- name: Koha Apt keys
  apt_key: url={{ item }} state=present
  with_items:
    - http://debian.koha-community.org/koha/gpg.asc
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Koha repos
  apt_repository: repo={{ item }} state=present
  with_items:
    - deb http://debian.koha-community.org/koha stable main

- name: Specify MySQL root password before installing
  debconf: name='mariadb-server' question='mysql-server/root_password' value='{{server0_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mariadb-server' question='mysql-server/root_password_again' value='{{server0_password | quote}}' vtype='password'
  become: true

- name: Koha packages
  apt:
    name:
      - 'mariadb-server'
      - 'koha-common'
      - 'python-pymysql'
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Port for Koha
  lineinfile:
    dest: /etc/koha/koha-sites.conf
    regexp: '^INTRAPORT='
    line: 'INTRAPORT="8088"'

- apache2_module:
    state: present
    name: rewrite

- apache2_module:
    state: present
    name: cgi

- name: Restart apache
  service:
    name: apache2 
    state: restarted
  