- name: Apt keys
  apt_key: url={{item}} state=present
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg

- name: Apt repos 
  apt_repository: repo={{item}} state=present
  with_items:
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    - ppa:webupd8team/java
    - ppa:hawq/shorewall

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Unwanted packages
  apt:
    state: absent
    update_cache: yes
    purge: yes
    name: ['docker', 'docker-engine', 'docker.io']
  
- name: Base packages
  apt: 
    name: ['vim', 'aptitude', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common','docker-ce', 'htop', 'python-pip', 'maven', 'python-passlib']
    state: latest 
    update_cache: yes

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: 
    name: ['oracle-java8-installer', 'ca-certificates', 'oracle-java8-set-default']
    state: latest

- name: Install ServerPack
  apt: state=present deb=https://raw.githubusercontent.com/ziobombo/ServerPack/mvn-repo/it/fraguglia/ServerPack/1.0.1/ServerPack-1.0.1.deb
  when: ansible_nodename == "server0"

- name: Install PhotoExport
  apt: state=present deb=wget https://github.com/ziobombo/PhotosExport/raw/mvn-repo/it/fraguglia/PhotosExport/1.4.0/PhotosExport-1.4.0.deb
  when: ansible_nodename == "cubo"

- name: docker-py (pip)
  pip:
    name: ['pip', 'docker', 'docker-compose']
    state: latest

- name: Ensure group "server0" exists
  group:
    name: server0
    state: present
    gid: 20000

- name: Ensure user "server0" exists
  user:
    name: server0
    uid: 20000
    group: server0
    home: /home/server0
    password: $6$6xL4lgJDf8PEss1$sYKCnrc8sEkE9.adtHv6K0EpAEf4In6HqSvdc4zDqUQE3b331pM7qt9e/9mZjID/ZGiqh4WUcmNOFUcpi1BxH1 
    shell: /bin/bash

- name: Variables in sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: 'net.core.rmem_max', value: '4194394' }
    - { name: 'net.core.wmem_max', value: '1048576' }

