- name: Ensure groups exist
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.id }}"
  with_items:
    - { name: server0, id: 20000 }
    - { name: riccardo, id: 20001 }

- name: Ensure users exist
  user:
    name: "{{ item.name }}"
    uid: "{{ item.id }}"
    group: "{{ item.group }}"
    home: /home/{{ item.name }}
    shell: /bin/bash
  with_items:
    - { name: server0, id: 20000, group: server0 }
    - { name: riccardo, id: 20001, group: riccardo }

- name: Base packages
  apt:
    name:
      - 'openjdk-11-jdk-headless'
      - 'iperf3'
      - 'sysfsutils'
      - 'htop'
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2