- name: Ensure group "server0" exists
  group:
    name: server0
    state: present
    gid: 20000

- name: Ensure user "server0" exists
  user:
    name: server0
    uid: 20000
    group: server0
    home: /home/server0
    shell: /bin/bash

- name: Base packages
  apt:
    name:
      - 'openjdk-11-jdk-headless'
      - 'iperf3'
      - 'sysfsutils'
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2