- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Ensure groups exist
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.id }}"
  with_items:
    - { name: server0, id: 20000 }
    - { name: riccardo, id: 20001 }

- name: Ensure users exist
  user:
    name: "{{ item.name }}"
    uid: "{{ item.id }}"
    group: "{{ item.group }}"
    home: /home/{{ item.name }}
    groups: "{{ item.groups }}"
    shell: /bin/bash
  with_items:
    - { name: server0, id: 20000, group: server0, groups: server0 }
    - { name: riccardo, id: 20001, group: riccardo, groups: server0 }

- name: Base packages
  apt:
    name:
      - 'sysfsutils'
      - 'htop'
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Ensure .config/htop exists
  file:
    path: /root/.config/htop
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: '0700'

- name: Ensure .config/htop exists for users
  file:
    path: /home/{{ item }}/.config/htop
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    recurse: yes
    mode: '0700'
  with_items:
    - server0
    - riccardo

- name: htop conf
  template:
    src: htoprc.j2
    dest: /root/.config/htop/htoprc
    owner: root
    group: root
    mode: '0644'

- name: htop conf for users
  template:
    src: htoprc.j2
    dest: /home/{{ item }}/.config/htop/htoprc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items:
    - server0
    - riccardo
