---
- name: Shorewall to be stopped
  service:
    name: shorewall
    state: stopped

- name: Docker images
  docker_service:
    project_name: fragugliaserver
    pull: true
    restarted: true
    definition:
      version: '3.7'
      services:
        sickrage:
          container_name: sickrage
          image: linuxserver/sickrage:latest
          volumes:
            - /home/server0/configuration/SickRage:/config
            - /home/server0/temp/t_downloads/complete:/downloads
            - /home/server0/data/tvshows:/tv
          environment:
            - PGID=20000
            - PUID=20000
            - TZ=Europe/Paris
          network_mode: "host"
          restart: always
        transmission:
          container_name: transmission
          image: linuxserver/transmission:latest
          volumes:
            - /home/server0/configuration/Transmission:/config
            - /home/server0/temp/t_downloads:/downloads
          environment:
            - PGID=20000
            - PUID=20000
            - TZ=Europe/Paris
          network_mode: "host"
          restart: always
        plex:
          container_name: plex
          image: linuxserver/plex
          volumes:
            - /home/server0/configuration/Plex:/config
            - /home/server0/data/tvshows:/data/tvshows
            - /home/server0/data/movies:/data/movies
            - /home/server0/temp/p_transcode:/transcode
          environment:
            - PGID=20000
            - PUID=20000
            - TZ=Europe/Paris
            - VERSION=latest
          network_mode: "host"
          restart: always
                
- name: Home for server0 exists
  file:
    path: /home/server0
    owner: server0
    group: server0
    recurse: true
    state: directory
